FROM golang:1.20.5 AS go-builder

WORKDIR /app

COPY go.mod .
COPY cmd cmd/
COPY internal internal/
COPY pkg pkg/
COPY vendor vendor/

RUN CGO_ENABLED=0 GOOS=linux go build --mod=vendor -o ./frontend ./cmd/frontend

FROM alpine:3.18.2 AS frontend

WORKDIR /app
COPY --from=go-builder /app/frontend /app/
