FROM golang:1.20.5 AS go-builder

WORKDIR /app

COPY go.mod .
COPY cmd cmd/
COPY internal internal/
COPY pkg pkg/
COPY vendor vendor/

RUN CGO_ENABLED=0 GOOS=linux go build --mod=vendor -o ./backend ./cmd/backend

FROM alpine:3.18.2 AS backend

WORKDIR /app
COPY --from=go-builder /app/backend /app/
